#!/bin/bash

# Jump to the current project's root directory (the one containing
# .git/)
topgit() {
if [[ -e .git || $(pwd) -ef / ]]; then
    echo -n
else
    cd ..
    topgit
fi
}

echo "Running post-merge hook..."
topgit

SUBMODULES=$(grep path .gitmodules | sed -r 's/^\s+path = //')

# Finding the submodules that have been modified
MOD_SUBMODULES=$(git diff --name-only | grep -F "$SUBMODULES")

# If no modified submodules, exit with status code 0, else prompt the
# user and exit accordingly
if [[ -n "$MOD_SUBMODULES" ]]; then
    echo "The following submodules have been updated in HEAD:"
    echo "$MOD_SUBMODULES"
    echo -n "Run git-submodule update? [n] "
    read -n 1 reply </dev/tty
    echo
    if [[ "$reply" == "y" || "$reply" == "Y" ]]; then
        git submodule update
    fi
fi




